//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration {
    
    public partial class UploadPhoto {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlTableRow trPhotoImage;
        protected System.Web.UI.WebControls.Label lblCurrentPhoto;
        protected System.Web.UI.WebControls.Image imgPhoto;
        protected System.Web.UI.WebControls.Label lblUploadPhoto;
        protected System.Web.UI.WebControls.FileUpload UserPhoto;
        protected System.Web.UI.WebControls.Label Label9;
        protected System.Web.UI.WebControls.CheckBox cbDisplayPhoto;
        protected System.Web.UI.WebControls.Label InjectScript;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
