//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.RetailSite {
    
    public partial class InputPage {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label Label1;
        protected Telerik.WebControls.RadNumericTextBox tbValue;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tbValue_err;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.TextBox tbAddress1;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.TextBox tbAddress2;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.TextBox tbCity;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.DropDownList ddlState;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ddlState_err;
        protected System.Web.UI.WebControls.Label Label6;
        protected Telerik.WebControls.RadMaskedTextBox tbZip;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tbZip_err;
        protected System.Web.UI.WebControls.Label Label7;
        protected System.Web.UI.WebControls.DropDownList ddlCounty;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ddlCounty_err;
        protected System.Web.UI.WebControls.Label Label8;
        protected Telerik.WebControls.RadDateInput rdidob1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl rdidob1_err;
        protected System.Web.UI.WebControls.Label Label9;
        protected Telerik.WebControls.RadDateInput rdidob2;
        protected System.Web.UI.HtmlControls.HtmlGenericControl rdidob2_err;
        protected System.Web.UI.WebControls.Label Label10;
        protected System.Web.UI.WebControls.TextBox tbLiens;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tbLiens_err;
        protected System.Web.UI.WebControls.Label Label11;
        protected System.Web.UI.WebControls.TextBox tbFirstName;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tbFirstName_err;
        protected System.Web.UI.WebControls.Label Label12;
        protected System.Web.UI.WebControls.TextBox tbLastName;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tbLastName_err;
        protected System.Web.UI.WebControls.Label Label13;
        protected Telerik.WebControls.RadMaskedTextBox tbPhone;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCalculate;
    }
}
