//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.RetailSiteTemplate {
    
    public partial class RetailPage {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.WebControls.RadWindowManager wm1;
        protected Telerik.WebControls.RadWindow RsAdvCalculator1;
        protected Telerik.WebControls.RadWindow RsAdvCalculator;
        protected LoanStarPortal.RetailSite.Control.Header Header1;
        protected System.Web.UI.WebControls.Panel Panel1;
        protected LoanStarPortal.RetailSite.Control.Footer Footer1;
        protected Telerik.WebControls.RadAjaxManager RadAjaxManager1;
    }
}
