//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.RetailSite.Control {
    
    public partial class Calculator {
        protected System.Web.UI.WebControls.Panel pnlInput;
        protected System.Web.UI.WebControls.Label Label11;
        protected System.Web.UI.WebControls.TextBox tbFirstName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox tbLastName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.Button btnOk;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Panel PanelAdvancedCalculator;
        protected System.Web.UI.WebControls.LinkButton lbDownload;
        protected System.Web.UI.WebControls.LinkButton lbMontlyProduct;
        protected System.Web.UI.WebControls.LinkButton lbAnnualProduct;
        protected System.Web.UI.WebControls.LinkButton lbHomeKeeperProduct;
        protected System.Web.UI.WebControls.Button btnDownloadMontly;
        protected System.Web.UI.WebControls.Button btnDownloadAnnual;
        protected System.Web.UI.WebControls.Button btnDownloadHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbInitialRateMontly;
        protected System.Web.UI.WebControls.TextBox tbInitialRateAnnual;
        protected System.Web.UI.WebControls.TextBox tbInitialRateHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbExpectedIntRateMontly;
        protected System.Web.UI.WebControls.TextBox tbExpectedIntRateAnnual;
        protected System.Web.UI.WebControls.TextBox tbExpectedIntRateHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbRateCupMontly;
        protected System.Web.UI.WebControls.TextBox tbRateCupAnnual;
        protected System.Web.UI.WebControls.TextBox tbRateCupHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbMontlyServiceFeeMontly;
        protected System.Web.UI.WebControls.TextBox tbMontlyServiceFeeAnnual;
        protected System.Web.UI.WebControls.TextBox tbMontlyServiceHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbHomeValueMontly;
        protected System.Web.UI.WebControls.TextBox tbHomeValueAnnual;
        protected System.Web.UI.WebControls.TextBox tbHomeValueHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbPledgedValueMonthly;
        protected System.Web.UI.WebControls.TextBox tbPledgedValueAnnual;
        protected System.Web.UI.WebControls.TextBox tbPledgedValueHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbPercentageMonthly;
        protected System.Web.UI.WebControls.TextBox tbPercentageAnnual;
        protected System.Web.UI.WebControls.TextBox tbPercentageHomeKeeper;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr1;
        protected System.Web.UI.WebControls.TextBox tbCreditlineGrowthRateMonthly;
        protected System.Web.UI.WebControls.TextBox tbCreditlineGrowthRateAnnual;
        protected System.Web.UI.WebControls.TextBox tbCreditlineGrowthRateHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbAgeMonthly;
        protected System.Web.UI.WebControls.TextBox tbAgeAnnual;
        protected System.Web.UI.WebControls.TextBox tbAgeHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbPrincipalLimitMontly;
        protected System.Web.UI.WebControls.TextBox tbPrincipalLimitAnnual;
        protected System.Web.UI.WebControls.TextBox tbPresentValueServiceFeeMontly;
        protected System.Web.UI.WebControls.TextBox tbPresentValueServiceFeeAnnual;
        protected System.Web.UI.WebControls.TextBox tbPresentValueServiceFeeHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbUpFrontPremiumMontly;
        protected System.Web.UI.WebControls.TextBox tbUpFrontPremiumAnnual;
        protected System.Web.UI.WebControls.TextBox tbUpFrontPremiumHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbFinancedOriginationFeeMonthly;
        protected System.Web.UI.WebControls.TextBox tbFinancedOriginationFeeAnnual;
        protected System.Web.UI.WebControls.TextBox tbFinancedOriginationFeeHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbTotalOtherClosingCostsMontly;
        protected System.Web.UI.WebControls.TextBox tbTotalOtherClosingCostsAnnual;
        protected System.Web.UI.WebControls.TextBox tbTotalOtherClosingCostsHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbTotalInitialChargesMontly;
        protected System.Web.UI.WebControls.TextBox tbTotalInitialChargesAnnual;
        protected System.Web.UI.WebControls.TextBox tbTotalInitialChargesHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbExistingMortgageBalanceMontly;
        protected System.Web.UI.WebControls.TextBox tbExistingMortgageBalanceAnnual;
        protected System.Web.UI.WebControls.TextBox tbExistingMortgageBalanceHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbTaxInsSetAsideMontly;
        protected System.Web.UI.WebControls.TextBox tbTaxInsSetAsideAnnual;
        protected System.Web.UI.WebControls.TextBox tbTaxInsSetAsideHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbNetAvailableMontly;
        protected System.Web.UI.WebControls.TextBox tbNetAvailableAnnual;
        protected System.Web.UI.WebControls.TextBox tbNetAvailableHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbUnallocatedFundsMontly;
        protected System.Web.UI.WebControls.TextBox tbUnallocatedFundsAnnual;
        protected System.Web.UI.WebControls.TextBox tbUnallocatedFundsHomeKeeper;
        protected System.Web.UI.WebControls.CheckBox chkInitialDraw;
        protected Telerik.WebControls.RadNumericTextBox tbInitialDrawAmount;
        protected System.Web.UI.WebControls.TextBox tbInitialDrawMontly;
        protected System.Web.UI.WebControls.TextBox tbInitialDrawAnnual;
        protected System.Web.UI.WebControls.TextBox tbInitialDrawHomeKeeper;
        protected System.Web.UI.WebControls.CheckBox chkCreditLine;
        protected Telerik.WebControls.RadNumericTextBox tbCreditLine;
        protected System.Web.UI.WebControls.TextBox tbCreditLineMontly;
        protected System.Web.UI.WebControls.TextBox tbCreditLineAnnual;
        protected System.Web.UI.WebControls.TextBox tbCreditLineHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbPeriodicPaymentMontly;
        protected System.Web.UI.WebControls.TextBox tbPeriodicPaymentAnnual;
        protected System.Web.UI.WebControls.TextBox tbPeriodicPaymentHomeKeeper;
        protected System.Web.UI.WebControls.TextBox tbFinalTermMontly;
        protected System.Web.UI.WebControls.TextBox tbFinalTermAnnual;
        protected System.Web.UI.WebControls.TextBox tbFinalTermHomeKeeper;
        protected System.Web.UI.WebControls.CheckBox chkMonthlyIncome;
        protected System.Web.UI.HtmlControls.HtmlTableRow trMonthlyIncome;
        protected System.Web.UI.WebControls.RadioButtonList rbMontlyIncome;
        protected System.Web.UI.HtmlControls.HtmlTableRow trTerm;
        protected Telerik.WebControls.RadNumericTextBox tbAmount;
        protected Telerik.WebControls.RadNumericTextBox tbMonths;
        protected System.Web.UI.WebControls.Button btnCalculate;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnBack;
    }
}
