//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMailPro.classic {
    
    public partial class Toolbar {
        protected System.Web.UI.WebControls.PlaceHolder Search;
        protected System.Web.UI.HtmlControls.HtmlInputText smallLookFor;
        protected System.Web.UI.WebControls.DropDownList DropDownListFolders;
        protected System.Web.UI.WebControls.PlaceHolder BackToList;
        protected System.Web.UI.WebControls.PlaceHolder BackToFollowUp;
        protected System.Web.UI.WebControls.PlaceHolder NewMessage;
        protected System.Web.UI.WebControls.PlaceHolder CheckMail;
        protected System.Web.UI.WebControls.PlaceHolder ReloadFoldersTree;
        protected System.Web.UI.WebControls.PlaceHolder Reply;
        protected System.Web.UI.WebControls.PlaceHolder Forward;
        protected System.Web.UI.WebControls.PlaceHolder MarkAsRead;
        protected System.Web.UI.WebControls.PlaceHolder MoveToFolder;
        protected System.Web.UI.WebControls.PlaceHolder EmptyTrash;
        protected System.Web.UI.WebControls.PlaceHolder Send;
        protected System.Web.UI.WebControls.PlaceHolder Print;
        protected System.Web.UI.WebControls.PlaceHolder Save;
        protected System.Web.UI.WebControls.PlaceHolder DeletePop;
        protected System.Web.UI.WebControls.PlaceHolder DeleteImap;
        protected System.Web.UI.WebControls.PlaceHolder Importance;
        protected System.Web.UI.WebControls.PlaceHolder NewMessageContacts;
        protected System.Web.UI.WebControls.PlaceHolder NewContact;
        protected System.Web.UI.WebControls.PlaceHolder NewGroup;
        protected System.Web.UI.WebControls.PlaceHolder AddContactsTo;
        protected System.Web.UI.WebControls.PlaceHolder PlaceholderContacts;
        protected System.Web.UI.WebControls.PlaceHolder ImportContacts;
        protected System.Web.UI.WebControls.PlaceHolder SearchContacts;
        protected System.Web.UI.WebControls.DropDownList DropDownListGroups;
        protected System.Web.UI.WebControls.PlaceHolder PreviousMsg;
        protected System.Web.UI.WebControls.PlaceHolder NextMsg;
    }
}
