//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class DocFieldMapping {
        protected Telerik.WebControls.RadAjaxManager RadAjaxManager1;
        protected System.Web.UI.WebControls.HiddenField dtvFormatType;
        protected System.Web.UI.WebControls.DropDownList ddlMPFieldGroup;
        protected System.Web.UI.WebControls.DropDownList ddlUnBoundFieldRegion;
        protected Telerik.WebControls.RadGrid MPFieldsGrid;
        protected System.Web.UI.WebControls.Label lblActionInfoArea;
        protected System.Web.UI.WebControls.Button btnBound;
        protected System.Web.UI.WebControls.Button btnUnBound;
        protected Telerik.WebControls.RadGrid DTUnBoundFieldsGrid;
        protected Telerik.WebControls.RadGrid DTBoundFieldsGrid;
    }
}
