//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class EditRuleTask {
        protected System.Web.UI.WebControls.Label lblHeader;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdruleexp;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox tbTitle;
        protected System.Web.UI.WebControls.Label tbTitleErr;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.TextBox tbDescription;
        protected System.Web.UI.WebControls.Label tbDescriptionErr;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.DropDownList ddlTaskType;
        protected System.Web.UI.WebControls.Label ddlTaskTypeErr;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.DropDownList ddlInfoSource;
        protected System.Web.UI.WebControls.Label ddlInfoSourceErr;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.DropDownList ddlDifficulty;
        protected System.Web.UI.WebControls.Label ddlDifficultyErr;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnSave;
        protected Telerik.WebControls.RadGrid G;
        protected System.Web.UI.WebControls.Button btnClose;
    }
}
