//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class EditRule {
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label lblValue;
        protected System.Web.UI.WebControls.CheckBox cbNot;
        protected System.Web.UI.WebControls.DropDownList ddlLogicalOp;
        protected System.Web.UI.WebControls.DropDownList ddlGroup;
        protected System.Web.UI.WebControls.DropDownList ddlField;
        protected System.Web.UI.WebControls.DropDownList ddlCompareOp;
        protected System.Web.UI.WebControls.TextBox tbValue;
        protected System.Web.UI.WebControls.DropDownList ddlDictionary;
        protected Telerik.WebControls.RadDatePicker dpValue;
        protected Telerik.WebControls.RadMaskedTextBox mtb;
        protected System.Web.UI.WebControls.Label validatormsg;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnAdd;
        protected Telerik.WebControls.RadGrid G;
        protected System.Web.UI.WebControls.Label Label6;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdexpr;
    }
}
