//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class EditMailSettings {
        protected System.Web.UI.WebControls.Label lblGeneralErr;
        protected System.Web.UI.WebControls.Label lblPOP3Server;
        protected System.Web.UI.WebControls.TextBox tbPOP3Server;
        protected System.Web.UI.WebControls.Label lblErrPOP3Server;
        protected System.Web.UI.WebControls.Label lblPOP3Port;
        protected System.Web.UI.WebControls.TextBox tbPOP3Port;
        protected System.Web.UI.WebControls.Label lblErrPOP3Port;
        protected System.Web.UI.WebControls.Label lblGlobalAdmin;
        protected System.Web.UI.WebControls.TextBox tbSMTPServer;
        protected System.Web.UI.WebControls.Label lblErrSMTPServer;
        protected System.Web.UI.WebControls.TextBox tbSMTPPort;
        protected System.Web.UI.WebControls.Label lblErrSMTPPort;
        protected System.Web.UI.WebControls.Button btnTest;
        protected System.Web.UI.WebControls.Label lblInfo;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
