//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class LenderProduct {
        protected System.Web.UI.WebControls.Label lblHeader;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label lblServicer;
        protected System.Web.UI.WebControls.Repeater rpServicer;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label lblInvestor;
        protected System.Web.UI.WebControls.Repeater rpInvestor;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label lblTrustee;
        protected System.Web.UI.WebControls.Repeater rpTrustee;
        protected System.Web.UI.WebControls.Button btnBack;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
