//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class LoggedAs {
        protected System.Web.UI.WebControls.Label lblLoggedAs;
        protected System.Web.UI.HtmlControls.HtmlTableRow trlogout;
        protected System.Web.UI.WebControls.LinkButton lbLogout;
    }
}
