//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class MpStatus {
        protected System.Web.UI.UpdatePanel UpdatePanel1;
        protected Telerik.WebControls.RadGrid G;
        protected System.Web.UI.WebControls.Label lblAction;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList ddlMPStatus1;
        protected System.Web.UI.WebControls.Label ddl1err;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.DropDownList ddlMPStatus2;
        protected System.Web.UI.WebControls.Label ddl2err;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
