//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Administration.Controls {
    
    public partial class ViewRequiredFields {
        protected System.Web.UI.WebControls.Panel pnlRf;
        protected System.Web.UI.WebControls.Label lblHeader;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList ddlStatus;
        protected Telerik.WebControls.RadTabStrip RadTabStrip1;
        protected Telerik.WebControls.RadMultiPage RadMultiPage1;
        protected System.Web.UI.WebControls.Button btnSave;
        protected Telerik.WebControls.RadAjaxManager RadAjaxManager1;
    }
}
