//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal {
    
    public partial class AdvCalculator {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.HiddenField hfAdvCalcUniqueID;
        protected System.Web.UI.WebControls.Literal ltrUnallocatedFunds;
        protected System.Web.UI.WebControls.RadioButton rbtnIncreaseInitialDraw;
        protected System.Web.UI.WebControls.Literal ltrInitialDraw;
        protected System.Web.UI.WebControls.RadioButton rbtnIncreaseCreditLine;
        protected System.Web.UI.WebControls.Literal ltrCreditLine;
        protected System.Web.UI.WebControls.RadioButton rbtnApplyTenure;
        protected System.Web.UI.WebControls.Literal ltrTenure;
        protected System.Web.UI.WebControls.Panel pnlTermPayment;
        protected System.Web.UI.WebControls.RadioButton rbtnTermPayment;
        protected System.Web.UI.WebControls.Literal ltrlTermPayment;
        protected System.Web.UI.WebControls.Button btnOk;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
