//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal {
    
    public partial class Test {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox tbMortgageId;
        protected System.Web.UI.WebControls.Label lblResult;
        protected System.Web.UI.WebControls.Label lblErr;
        protected System.Web.UI.WebControls.Button btnMap;
        protected System.Web.UI.WebControls.TextBox TextBox1;
    }
}
