//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal {
    
    public partial class VendorDashBoard {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.WebControls.RadMenu rmVendor;
        protected System.Web.UI.WebControls.Image Image1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.LinkButton lbLogout;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.PlaceHolder phVendorControl;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSave;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnBack;
    }
}
