//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class ApplicantList {
        protected Telerik.WebControls.RadSplitter RadSplitter2;
        protected Telerik.WebControls.RadPane TopPane;
        protected System.Web.UI.WebControls.RadioButton rbAllLoans;
        protected System.Web.UI.WebControls.RadioButton rbMyPipeline;
        protected Telerik.WebControls.RadComboBox ddlDisplay;
        protected Telerik.WebControls.RadComboBox ddlGroup;
        protected Telerik.WebControls.RadComboBox dllSort;
        protected Telerik.WebControls.RadSplitBar RadSplitBar3;
        protected Telerik.WebControls.RadPane MiddlePane;
        public Telerik.WebControls.RadPanelbar RadPBMortgages;
    }
}
