//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class Calculator {
        protected Telerik.WebControls.RadSplitter RadSplitter2;
        protected Telerik.WebControls.RadPane TopPane;
        protected Telerik.WebControls.RadTabStrip rtsCalculators;
        protected Telerik.WebControls.Tab advCalc;
        protected Telerik.WebControls.RadSplitBar RadSplitBar3;
        protected Telerik.WebControls.RadPane MiddlePane;
        protected Telerik.WebControls.RadMultiPage rmpCalculator;
        protected Telerik.WebControls.PageView pvAdvCalc;
    }
}
