//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class Followup {
        protected Telerik.WebControls.RadSplitter RadSplitter2;
        protected Telerik.WebControls.RadPane TopPane;
        protected Telerik.WebControls.RadTabStrip rtsFollowup;
        protected Telerik.WebControls.Tab tabConditions;
        protected Telerik.WebControls.Tab tabCampaigns;
        protected Telerik.WebControls.RadSplitBar RadSplitBar3;
        protected Telerik.WebControls.RadPane Radpane1;
        protected Telerik.WebControls.RadMultiPage rmpFollowup;
        protected Telerik.WebControls.PageView pvConditions;
        protected LoanStarPortal.Controls.FollowupConditions FollowupConditions1;
        protected Telerik.WebControls.PageView pvCampaign;
        protected LoanStarPortal.Controls.FollowupCampaign FollowupCampaign1;
    }
}
