//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class FollowupConditions {
        protected Telerik.WebControls.RadSplitter RadSplitter2;
        protected Telerik.WebControls.RadPane TopPane;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected Telerik.WebControls.RadSplitBar RadSplitBar3;
        protected Telerik.WebControls.RadPane MiddlePane;
        protected System.Web.UI.WebControls.Panel PanelTasks;
        protected Telerik.WebControls.RadGrid gridConditions;
        protected System.Web.UI.WebControls.LinkButton btnAddCondition;
        protected System.Web.UI.WebControls.TextBox tbCondTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
        protected System.Web.UI.WebControls.TextBox tbCondDesc;
        protected System.Web.UI.WebControls.DropDownList ddlAuthLevel;
        protected System.Web.UI.WebControls.Label lblAuthLevel;
        protected System.Web.UI.WebControls.Button btnSatisfy;
        protected System.Web.UI.WebControls.Button btnSubmitCond;
        protected System.Web.UI.WebControls.DropDownList ddlRecurrence;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
        protected Telerik.WebControls.RadDatePicker rdpStartDate;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        protected System.Web.UI.WebControls.Label lblNextWorkDate;
        protected System.Web.UI.WebControls.Button btnSubmitFollow;
        protected System.Web.UI.HtmlControls.HtmlTable tblNotes;
        protected System.Web.UI.WebControls.TextBox tbNote;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.DropDownList ddlAction;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.Button btnShowNotes;
        protected System.Web.UI.WebControls.Button btnSubmitNote;
        protected System.Web.UI.WebControls.Panel PanelEmailAdd;
        protected LoanStarPortal.Controls.EmailAdd EmailAdd1;
        protected System.Web.UI.WebControls.Panel PanelUnderwriter;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCredit;
        protected System.Web.UI.WebControls.CheckBox chkCredit;
        protected System.Web.UI.WebControls.Button btnPrintCCDE;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProperty;
        protected System.Web.UI.WebControls.CheckBox chkProperty;
        protected System.Web.UI.WebControls.Button btnPrintDE;
    }
}
