//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class MortgageTab {
        protected Telerik.WebControls.RadSplitter RadSplitter2;
        protected Telerik.WebControls.RadPane TopPane;
        protected System.Web.UI.WebControls.Label lblMortgageName;
        protected System.Web.UI.WebControls.Label lblCity;
        protected System.Web.UI.WebControls.Label lblCounty;
        protected System.Web.UI.WebControls.Label lblState;
        protected System.Web.UI.WebControls.Label lblProduct;
        protected System.Web.UI.WebControls.Label lblProfileStatus;
        protected Telerik.WebControls.RadSplitBar RadSplitBar3;
        protected Telerik.WebControls.RadPane Radpane1;
        protected Telerik.WebControls.RadTabStrip TabsMortgageProfiles;
        protected Telerik.WebControls.Tab tabBorrower;
        protected Telerik.WebControls.Tab tabProperty;
        protected Telerik.WebControls.Tab tabMortgage;
        protected Telerik.WebControls.Tab tabLender;
        protected Telerik.WebControls.RadPane MiddlePane;
        protected Telerik.WebControls.RadMultiPage RadMultiPage1;
        protected Telerik.WebControls.PageView pvBorrower;
        protected Telerik.WebControls.PageView pvProperty;
        protected Telerik.WebControls.PageView pvMortgage;
        protected Telerik.WebControls.PageView pvLender;
        protected Telerik.WebControls.RadSplitBar RadSplitBar1;
        protected Telerik.WebControls.RadPane BottomPane;
    }
}
