//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class MortgagePrepaidItems {
        protected System.Web.UI.WebControls.Panel Panel1;
        protected System.Web.UI.WebControls.GridView gPrepaidItems;
    }
}
