//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStarPortal.Controls {
    
    public partial class ViewVendors {
        protected System.Web.UI.HtmlControls.HtmlTableRow gridtr;
        protected Telerik.WebControls.RadGrid gVendors;
        protected System.Web.UI.HtmlControls.HtmlTableRow detailstr;
        protected Telerik.WebControls.RadTabStrip VendorInfo;
        protected Telerik.WebControls.Tab tabBasicInfo;
        protected Telerik.WebControls.Tab tabContacts;
        protected Telerik.WebControls.Tab tab1;
        protected Telerik.WebControls.RadMultiPage RadMultiPage1;
        protected Telerik.WebControls.PageView pvbasicInfo;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.TextBox tbCompanyName;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox tbCorporateAddress1;
        protected System.Web.UI.WebControls.Label Label16;
        protected System.Web.UI.WebControls.TextBox tbCorporateAddress2;
        protected System.Web.UI.WebControls.Label Label27;
        protected Telerik.WebControls.RadMaskedTextBox tbCompanyPhone;
        protected System.Web.UI.WebControls.Label Label15;
        protected Telerik.WebControls.RadMaskedTextBox tbCompanyFax;
        protected System.Web.UI.WebControls.Label Label28;
        protected System.Web.UI.WebControls.TextBox tbCompanyEmail;
        protected System.Web.UI.WebControls.Label Label18;
        protected System.Web.UI.WebControls.TextBox tbCompanyCity;
        protected System.Web.UI.WebControls.Label Label19;
        protected System.Web.UI.WebControls.DropDownList ddlCompanyState;
        protected System.Web.UI.WebControls.Label Label20;
        protected System.Web.UI.WebControls.TextBox tbCompanyZip;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.TextBox tbBillingAddress1;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.TextBox tbBillingAddress2;
        protected System.Web.UI.WebControls.Label Label30;
        protected System.Web.UI.WebControls.TextBox tbBillingCity;
        protected System.Web.UI.WebControls.Label Label31;
        protected System.Web.UI.WebControls.DropDownList ddlBillingState;
        protected System.Web.UI.WebControls.Label Label32;
        protected Telerik.WebControls.RadMaskedTextBox tbBillingZip;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.TextBox tbPrimaryContact;
        protected System.Web.UI.WebControls.Label Label6;
        protected Telerik.WebControls.RadMaskedTextBox tbPCPhone1;
        protected System.Web.UI.WebControls.Label Label7;
        protected Telerik.WebControls.RadMaskedTextBox tbPCPhone2;
        protected System.Web.UI.WebControls.Label Label8;
        protected System.Web.UI.WebControls.TextBox tbPCEmail;
        protected System.Web.UI.WebControls.Label Label9;
        protected System.Web.UI.WebControls.TextBox tbSecondaryContact;
        protected System.Web.UI.WebControls.Label Label10;
        protected Telerik.WebControls.RadMaskedTextBox tbSCPhone1;
        protected System.Web.UI.WebControls.Label Label11;
        protected Telerik.WebControls.RadMaskedTextBox tbSCPhone2;
        protected System.Web.UI.WebControls.Label Label12;
        protected System.Web.UI.WebControls.TextBox tbSCEmail;
        protected System.Web.UI.WebControls.Label Label13;
        protected Telerik.WebControls.RadDateInput dtLicenseExpdate;
        protected System.Web.UI.WebControls.Label Label14;
        protected System.Web.UI.WebControls.CheckBox cbDisabled;
        protected Telerik.WebControls.PageView pvContacts;
        protected LoanStarPortal.Controls.VendorContacts VendorContacts1;
        protected Telerik.WebControls.PageView pvAffiliation;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Label Label17;
        protected System.Web.UI.WebControls.DropDownList ddlAffiliation;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAffiliation;
        protected System.Web.UI.WebControls.Label Label21;
        protected System.Web.UI.WebControls.TextBox tbAffiliation;
        protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
        protected System.Web.UI.WebControls.Button btnSaveAffiliation;
        protected System.Web.UI.HtmlControls.HtmlTableRow buttontr;
        protected System.Web.UI.WebControls.Button btnBack;
    }
}
